MVC-webapp/Models/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int ServiceID { get; set; }
        public int RoomNum { get; set; }
        public double ServicePrice { get; set; }
        public Nullable<System.DateTime> FirstDay { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public Nullable<int> Quantity { get; set; }
        public double OrderPrice { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> LoundryID { get; set; }
    
        public virtual Laundry Laundry { get; set; }
        public virtual RentCar RentCar { get; set; }
        public virtual Room Room { get; set; }
    }
}

MVC-webapp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_webapp.Models;
using MVC_webapp.Util;

namespace MVC_webapp.Controllers
{
    public class OrdersController : BaseController
    {
        private MVC_HotelProject2Entities db = new MVC_HotelProject2Entities();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Laundry).Include(o => o.RentCar).Include(o => o.Room);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return PartialView(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.LoundryID = new SelectList(db.Laundries, "LoundryID", "ServiceName");
            ViewBag.CarID = new SelectList(db.RentCars, "CarID", "CarBrand");
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,ServiceID,RoomNum,ServicePrice,FirstDay,LastDay,Quantity,OrderPrice,CarID,LoundryID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LoundryID = new SelectList(db.Laundries, "LoundryID", "ServiceName", order.LoundryID);
            ViewBag.CarID = new SelectList(db.RentCars, "CarID", "CarBrand", order.CarID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", order.RoomNum);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoundryID = new SelectList(db.Laundries, "LoundryID", "ServiceName", order.LoundryID);
            ViewBag.CarID = new SelectList(db.RentCars, "CarID", "CarBrand", order.CarID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", order.RoomNum);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,ServiceID,RoomNum,ServicePrice,FirstDay,LastDay,Quantity,OrderPrice,CarID,LoundryID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoundryID = new SelectList(db.Laundries, "LoundryID", "ServiceName", order.LoundryID);
            ViewBag.CarID = new SelectList(db.RentCars, "CarID", "CarBrand", order.CarID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", order.RoomNum);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC-webapp/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_webapp.Models;
using MVC_webapp.Util;

namespace MVC_webapp.Controllers
{
    public class RoomsController : BaseController
    {
        private MVC_HotelProject2Entities db = new MVC_HotelProject2Entities();

        // GET: Rooms
        public ActionResult Index()
        {
            return View(db.Rooms.ToList());
        }

        // GET: Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return PartialView(room);
        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoomNum,RoomInfo,RoomStatus,Extra,Type,RoomPrice")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room);
        }

        // GET: Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoomNum,RoomInfo,RoomStatus,Extra,Type,RoomPrice")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC-webapp/Views/Orders/Create.cshtml
@model MVC_webapp.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServicePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServicePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServicePrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstDay, htmlAttributes: new { @class = "control-label col-md-2" })


            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.FirstDay, new { htmlAttributes = new { @class = "form-control date" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

            <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
            </script>



            @Html.ValidationMessageFor(model => model.FirstDay, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastDay, htmlAttributes: new { @class = "control-label col-md-2" })


            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    @Html.EditorFor(model => model.LastDay, new { htmlAttributes = new { @class = "form-control date" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

            <script type="text/javascript">
            $(function () {
                $('#datetimepicker2').datetimepicker();
            });
            </script>



            @Html.ValidationMessageFor(model => model.LastDay, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarID, "CarID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoundryID, "LoundryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LoundryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoundryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href='@Url.Action("Index","Orders")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-webapp/Views/Orders/Delete.cshtml
@model MVC_webapp.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Laundry.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laundry.ServiceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentCar.CarBrand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentCar.CarBrand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomInfo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
       
            <input type="submit" value="Delete" class="btn btn-sx btn-danger" />
            <a href='@Url.Action("Index","Orders")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

        </div>
    }
</div>

MVC-webapp/Views/Orders/Details.cshtml
@model MVC_webapp.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Laundry.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laundry.ServiceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentCar.CarBrand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentCar.CarBrand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomInfo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC-webapp/Views/Orders/Edit.cshtml
@model MVC_webapp.Models.Order

@{
    ViewBag.Title = "Orders Edit";
}

<h2>Order</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderID)

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServicePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServicePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServicePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.FirstDay, new { htmlAttributes = new { @class = "form-control date" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>


                <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                </script>
                @Html.ValidationMessageFor(model => model.FirstDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.LastDay, new { htmlAttributes = new { @class = "form-control date" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>


                <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                </script>
                @Html.ValidationMessageFor(model => model.LastDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarID, "CarID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoundryID, "LoundryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LoundryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoundryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <a href='@Url.Action("Index","Orders")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-webapp/Views/Orders/Index.cshtml
@model IEnumerable<MVC_webapp.Models.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>

<p>
    <a href='@Url.Action("Create",null, Request.Url.Scheme)' class="yarimbutton btn btn-default btn-lg btn-success"><span class="lnr lnr-shirt"></span> Laundry </a>
    <a href='@Url.Action("Create",null, Request.Url.Scheme)' class = "yarimbutton btn btn-default btn-lg btn-success"><span class="lnr lnr-car"></span> Rent a Car </a >
</p>
<table class="table">
    <tr>
      
        <th>
            @Html.DisplayNameFor(model => model.RoomNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServicePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderPrice)
        </th>  
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoomNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ServicePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastDay)
        </td>
    
        <td>
            @Html.DisplayFor(modelItem => item.OrderPrice)
        </td>
       
        <td>
            <a href='@Url.Action("Edit","Rooms",new { id=item.RoomNum }, Request.Url.Scheme)' class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-edit"></span> Edit</a>
            <a href='@Url.Action("Details","Rooms", new { id=item.RoomNum }, Request.Url.Scheme)' class="btn btn-xs btn-info modal-link"><span class="glyphicon glyphicon-info-sign"></span> Details</a>
            <a href='@Url.Action("Delete","Rooms", new { id=item.RoomNum }, Request.Url.Scheme)' class="btn btn-sx btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</a>
        </td>
    </tr>

}

</table>