MVC-webapp/Models/CheckIn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckIn()
        {
            this.CheckOuts = new HashSet<CheckOut>();
        }
    
        public int CheckInID { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<int> NumOfReservedDays { get; set; }
        public int CustomerID { get; set; }
        public int RoomNum { get; set; }
        public Nullable<int> NoAdults { get; set; }
        public Nullable<int> NoChildren { get; set; }
        public int PassportNo { get; set; }
        public Nullable<int> checkoutstatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckOut> CheckOuts { get; set; }
    }
}

MVC-webapp/Controllers/CheckInsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_webapp.Models;
using MVC_webapp.Util;

namespace MVC_webapp.Controllers
{
    public class CheckInsController : BaseController
    {
        private MVC_HotelProject2Entities db = new MVC_HotelProject2Entities();

        // GET: CheckIns
        public ActionResult Index()
        {
            var checkIns = db.CheckIns.Include(c => c.Customer).Include(c => c.Room);
            return View(checkIns.ToList());
        }

        // GET: CheckIns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckIn checkIn = db.CheckIns.Find(id);
            if (checkIn == null)
            {
                return HttpNotFound();
            }
            return PartialView(checkIn);
        }

        // GET: CheckIns/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "Name");
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomNum");
            return View();
        }

        // POST: CheckIns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CheckInID,CheckInDate,NumOfReservedDays,CustomerID,RoomNum,NoAdults,NoChildren,PassportNo,checkoutstatus")] CheckIn checkIn)
        {
            if (ModelState.IsValid)
            {
                db.CheckIns.Add(checkIn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "Name", checkIn.CustomerID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomNum", checkIn.RoomNum);


            return View(checkIn);
        }

        // GET: CheckIns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckIn checkIn = db.CheckIns.Find(id);
            if (checkIn == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "Name", checkIn.CustomerID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomNum", checkIn.RoomNum);
            return View(checkIn);
        }





        // POST: CheckIns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CheckInID,CheckInDate,NumOfReservedDays,CustomerID,RoomNum,NoAdults,NoChildren,PassportNo,checkoutstatus")] CheckIn checkIn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkIn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "Name", checkIn.CustomerID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomNum", checkIn.RoomNum);
            return View(checkIn);
        }

        // GET: CheckIns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckIn checkIn = db.CheckIns.Find(id);
            if (checkIn == null)
            {
                return HttpNotFound();
            }
            return View(checkIn);
        }

        // POST: CheckIns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckIn checkIn = db.CheckIns.Find(id);
            db.CheckIns.Remove(checkIn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC-webapp/Views/CheckIns/Create.cshtml
@model MVC_webapp.Models.CheckIn

@{
    ViewBag.Title = "Create Checkin";
}

<h2>Checkin</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CheckInDate, htmlAttributes: new { @class = "control-label col-md-2" })
           
                
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            @Html.EditorFor(model => model.CheckInDate, new { htmlAttributes = new { @class = "form-control date" } })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
               
                <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                </script>
                
                
                
                 @Html.ValidationMessageFor(model => model.CheckInDate, "", new { @class = "text-danger" })
       
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfReservedDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfReservedDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfReservedDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoAdults, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoAdults, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoAdults, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoChildren, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoChildren, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoChildren, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassportNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassportNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassportNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.checkoutstatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.checkoutstatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.checkoutstatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href='@Url.Action("Index","CheckIns")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-webapp/Views/CheckIns/Delete.cshtml
@model MVC_webapp.Models.CheckIn

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheckIn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CheckInDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfReservedDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfReservedDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoAdults)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoAdults)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoChildren)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoChildren)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassportNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassportNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkoutstatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkoutstatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomInfo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-sx btn-danger" />
            <a href='@Url.Action("Index","CheckIns")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

        </div>
    }
</div>

MVC-webapp/Views/CheckIns/Details.cshtml
@model MVC_webapp.Models.CheckIn
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/modalstyles.css" rel="stylesheet" />


<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="~/Content/Site.css" rel="stylesheet" />
@*//yeni eklendi*@
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<link href="~/Content/icon-font.min.css" rel="stylesheet" />
<script src="~/Scripts/Chart.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<script src="~/Scripts/wow.min.js"></script>
<script>
    new WOW().init();
</script>
<link href='//fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>



<div class="boxbackcol">
    <div class="modal-title" style="color:#3A87AD;">
        <h2>Checkin Details</h2>
    </div>

    @using (Html.BeginForm("details", "CheckIns", FormMethod.Post))
    {

        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CheckInDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CheckInDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NumOfReservedDays)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NumOfReservedDays)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NoAdults)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NoAdults)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NoChildren)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NoChildren)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PassportNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PassportNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.checkoutstatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.checkoutstatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Customer.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Customer.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Room.RoomInfo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Room.RoomInfo)
                </dd>

            </dl>
        </div>
        <center>
            <p>
                <a href='@Url.Action("Edit","CheckIns",new { id=Model.CheckInID }, Request.Url.Scheme)' class="btn btn-xs btn-warning modaleditrenk"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                <a href='@Url.Action("Index","CheckIns")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </p>
        </center>
    }
</div>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/scripts.js"></script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#btnback').click(function () {
            $('modal-container').modal('hide');
        });
    });
</script>

MVC-webapp/Views/CheckIns/Edit.cshtml
@model MVC_webapp.Models.CheckIn

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckIn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CheckInID)

        <div class="form-group">
            @Html.LabelFor(model => model.CheckInDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.CheckInDate, new { htmlAttributes = new { @class = "form-control date" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>


                <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                </script>
                @Html.ValidationMessageFor(model => model.CheckInDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfReservedDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfReservedDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfReservedDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoAdults, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoAdults, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoAdults, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoChildren, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoChildren, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoChildren, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassportNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassportNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassportNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.checkoutstatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.checkoutstatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.checkoutstatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <a href='@Url.Action("Index","CheckIns")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-webapp/Views/CheckIns/Index.cshtml
@model IEnumerable<MVC_webapp.Models.CheckIn>

@{
    ViewBag.Title = "Check In";
}

<h2>Check In</h2>

<p>
    @Html.ActionLink("Check In Customer", "Create", null, new { @class = "btn btn-block btn-lg btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            Checkin Date
        </th>
        <th>
            Name
        </th>
        <th>
            Room Number
        </th>
        <th>
            Reserved Days
        </th>
        <th>
            Adults
        </th>
        <th>
            Children
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CheckInDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Room.RoomNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumOfReservedDays)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoAdults)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoChildren)
        </td>
        <td>
            <a href='@Url.Action("Edit","CheckIns",new { id=item.CheckInID }, Request.Url.Scheme)' class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-edit"></span> Edit</a>
            <a href='@Url.Action("Details","CheckIns", new { id=item.CheckInID }, Request.Url.Scheme)' class="btn btn-xs btn-info modal-link"><span class="glyphicon glyphicon-info-sign"></span> Details</a>
            <a href='@Url.Action("Delete","CheckIns", new { id=item.CheckInID }, Request.Url.Scheme)' class="btn btn-sx btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</a>

        </td>
    </tr>
}

</table>