MVC-webapp/Models/CheckOut.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int CheckOutID { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public int CheckInID { get; set; }
        public int RoomNum { get; set; }
        public int customerID { get; set; }
        public int noadults { get; set; }
        public Nullable<int> nochild { get; set; }
        public int passportnum { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Room Room { get; set; }
        public virtual Customer Customer { get; set; }
    }
}

MVC-webapp/Controllers/CheckOutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_webapp.Models;
using MVC_webapp.Util;

namespace MVC_webapp.Controllers
{
    public class CheckOutsController : BaseController
    {
        private MVC_HotelProject2Entities db = new MVC_HotelProject2Entities();

        // GET: CheckOuts
        public ActionResult Index()
        {
            var checkOuts = db.CheckOuts.Include(c => c.CheckIn).Include(c => c.Room).Include(c => c.Customer);
            return View(checkOuts.ToList());
        }

        // GET: CheckOuts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOut checkOut = db.CheckOuts.Find(id);
            if (checkOut == null)
            {
                return HttpNotFound();
            }
            return PartialView(checkOut);
        }

        // GET: CheckOuts/Create
        public ActionResult Create()
        {
            ViewBag.CheckInID = new SelectList(db.CheckIns, "CheckInID", "CheckInID");
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomNum");
            ViewBag.customerID = new SelectList(db.Customers, "CustomerID", "Name");
           
            return View();
        }

        // POST: CheckOuts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CheckOutID,CheckOutDate,CheckInID,RoomNum,customerID,noadults,nochild,passportnum")] CheckOut checkOut)
        {
            if (ModelState.IsValid)
            {
                db.CheckOuts.Add(checkOut);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CheckInID = new SelectList(db.CheckIns, "CheckInID", "CheckInID", checkOut.CheckInID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", checkOut.RoomNum);
            ViewBag.customerID = new SelectList(db.Customers, "CustomerID", "Name", checkOut.customerID);
            return View(checkOut);
        }

        // GET: CheckOuts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOut checkOut = db.CheckOuts.Find(id);
            if (checkOut == null)
            {
                return HttpNotFound();
            }
            ViewBag.CheckInID = new SelectList(db.CheckIns, "CheckInID", "CheckInID", checkOut.CheckInID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", checkOut.RoomNum);
            ViewBag.customerID = new SelectList(db.Customers, "CustomerID", "Name", checkOut.customerID);
            return View(checkOut);
        }

        // POST: CheckOuts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CheckOutID,CheckOutDate,CheckInID,RoomNum,customerID,noadults,nochild,passportnum")] CheckOut checkOut)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkOut).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CheckInID = new SelectList(db.CheckIns, "CheckInID", "CheckInID", checkOut.CheckInID);
            ViewBag.RoomNum = new SelectList(db.Rooms, "RoomNum", "RoomInfo", checkOut.RoomNum);
            ViewBag.customerID = new SelectList(db.Customers, "CustomerID", "Name", checkOut.customerID);
            return View(checkOut);
        }

        // GET: CheckOuts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOut checkOut = db.CheckOuts.Find(id);
            if (checkOut == null)
            {
                return HttpNotFound();
            }
            return View(checkOut);
        }

        // POST: CheckOuts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckOut checkOut = db.CheckOuts.Find(id);
            db.CheckOuts.Remove(checkOut);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC-webapp/Views/CheckOuts/Create.cshtml
@model MVC_webapp.Models.CheckOut


    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>CheckOut</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CheckOutDate, htmlAttributes: new { @class = "control-label col-md-2" })


                <div class="form-group">
                    <div class='input-group date' id='datetimepicker1'>
                        @Html.EditorFor(model => model.CheckOutDate, new { htmlAttributes = new { @class = "form-control date" } })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>

                <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                </script>



                @Html.ValidationMessageFor(model => model.CheckOutDate, "", new { @class = "text-danger" })

            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CheckInID, "CheckInID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CheckInID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CheckInID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.customerID, "customerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("customerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.customerID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.noadults, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.noadults, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noadults, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.nochild, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nochild, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nochild, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.passportnum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.passportnum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.passportnum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    <a href='@Url.Action("Index","Checkouts")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

                </div>
            </div>
        </div>
    }

MVC-webapp/Views/CheckOuts/Delete.cshtml
@model MVC_webapp.Models.CheckOut


    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>CheckOut</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CheckOutDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CheckOutDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.noadults)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.noadults)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.nochild)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.nochild)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.passportnum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.passportnum)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CheckIn.CheckInID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CheckIn.CheckInID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Room.RoomInfo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Room.RoomInfo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Customer.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                <a href='@Url.Action("Index","CheckOuts")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>
            </div>
        }
    </div>

MVC-webapp/Views/CheckOuts/Details.cshtml
@model MVC_webapp.Models.CheckOut
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/modalstyles.css" rel="stylesheet" />


<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="~/Content/Site.css" rel="stylesheet" />
@*//yeni eklendi*@
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<link href="~/Content/icon-font.min.css" rel="stylesheet" />
<script src="~/Scripts/Chart.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<script src="~/Scripts/wow.min.js"></script>
<script>
    new WOW().init();
</script>
<link href='//fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>



<div class="boxbackcol">
    <div class="modal-title" style="color:#3A87AD;">
        <h2>Checkout Details</h2>
    </div>

    @using (Html.BeginForm("details", "CheckOuts", FormMethod.Post))
    {
        <div>
          
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CheckOutDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CheckOutDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.noadults)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.noadults)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.nochild)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nochild)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.passportnum)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.passportnum)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CheckIn.CheckInID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CheckIn.CheckInID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Room.RoomInfo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Room.RoomInfo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Customer.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Customer.Name)
                </dd>

            </dl>
        </div>
 
        <center>
            <p>
                <a href='@Url.Action("Edit","CheckOuts",new { id=Model.CheckOutID }, Request.Url.Scheme)' class="btn btn-xs btn-warning modaleditrenk"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                <a href='@Url.Action("Index","CheckOuts")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

            </p>
        </center>
    }
</div>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/scripts.js"></script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#btnback').click(function () {
            $('modal-container').modal('hide');
        });
    });
</script>

MVC-webapp/Views/CheckOuts/Edit.cshtml
@model MVC_webapp.Models.CheckOut



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>CheckOut</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CheckOutID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.CheckOutDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">


                    <div class='input-group date' id='datetimepicker1'>
                        @Html.EditorFor(model => model.CheckOutDate, new { htmlAttributes = new { @class = "form-control date" } })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>


                    <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
                    </script>
                    @Html.ValidationMessageFor(model => model.CheckOutDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CheckInID, "CheckInID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CheckInID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CheckInID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.RoomNum, "RoomNum", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("RoomNum", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomNum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.customerID, "customerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("customerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.customerID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.noadults, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.noadults, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noadults, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.nochild, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nochild, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nochild, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.passportnum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.passportnum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.passportnum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    <a href='@Url.Action("Index","Chekouts")' class="btn  btn-sm btn-info"><span class="glyphicon glyphicon-backward"></span> Go Back</a>

                </div>
            </div>
        </div>
    }
    

MVC-webapp/Views/CheckOuts/Index.cshtml
@model IEnumerable<MVC_webapp.Models.CheckOut>

@{
    ViewBag.Title = "Check Out";
}


    <h2>Check Out</h2>
    <p>
        @Html.ActionLink("Check Out Customer", "Create", null, new { @class = "btn btn-block btn-lg btn-success" })
    </p>
    <table class="table">
        <tr>
            <th>
                Checkin Date
            </th>
            <th>
               Name
            </th>
            <th>
               Room Number
            </th>
            <th>
               Stayed Days
            </th>
            <th>
                Adult
            </th>
            <th>
                Children
            </th>
            <th>
               Checkout Date
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn.CheckInDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.RoomNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn.NumOfReservedDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn.NoAdults)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn.NoChildren)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckOutDate)
            </td>
            <td>
            
                <a href='@Url.Action("Edit","CheckOuts",new { id=item.CheckOutID }, Request.Url.Scheme)' class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                <a href='@Url.Action("Details","CheckOuts", new { id=item.CheckOutID }, Request.Url.Scheme)' class="btn btn-xs btn-info modal-link"><span class="glyphicon glyphicon-info-sign"></span> Details</a>
                <a href='@Url.Action("Delete","CheckOuts", new { id=item.CheckOutID }, Request.Url.Scheme)' class="btn btn-sx btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</a>

            </td>
        </tr>
    }
    
    </table>